insert into genre (parent_id, slug, name) values (null, 'genre-8g6qwo', 'Легкое чтение');
insert into genre (parent_id, slug, name) values (null, 'genre-9fszsq', 'Серьезное чтение');
insert into genre (parent_id, slug, name) values (null, 'genre-8kx7ek', 'Бизнес-книги');
insert into genre (parent_id, slug, name) values (null, 'genre-udnnqk', 'Знания и навыки');
insert into genre (parent_id, slug, name) values (1, 'genre-nulfa9', 'Детективы');
insert into genre (parent_id, slug, name) values (1, 'genre-l5vagr', 'Приключения');
insert into genre (parent_id, slug, name) values (1, 'genre-tmnn10', 'Любовные романы');
insert into genre (parent_id, slug, name) values (2, 'genre-kzz0n2', 'Современная проза');
insert into genre (parent_id, slug, name) values (2, 'genre-rm6xbv', 'Пьесы, драматургия');
insert into genre (parent_id, slug, name) values (2, 'genre-zokntm', 'Классическая литература');
insert into genre (parent_id, slug, name) values (3, 'genre-ygqeif', 'Финансы');
insert into genre (parent_id, slug, name) values (3, 'genre-wuvanv', 'Менеджмент');
insert into genre (parent_id, slug, name) values (3, 'genre-qaakme', 'Экономика');
insert into genre (parent_id, slug, name) values (4, 'genre-yww8hu', 'Культура и искусство');
insert into genre (parent_id, slug, name) values (4, 'genre-ati3ax', 'Учебная и научная литература');
insert into genre (parent_id, slug, name) values (4, 'genre-ndesyf', 'Компьютерная литература');
insert into genre (parent_id, slug, name) values (5, 'genre-alaixj', 'Исторические детективы');
insert into genre (parent_id, slug, name) values (5, 'genre-z07wn8', 'Современные детективы');
insert into genre (parent_id, slug, name) values (5, 'genre-y1gf1k', 'Триллеры');
insert into genre (parent_id, slug, name) values (5, 'genre-nvu6c4', 'Зарубежные детективы');
insert into genre (parent_id, slug, name) values (5, 'genre-vbfsy6', 'Классические детективы');
insert into genre (parent_id, slug, name) values (6, 'genre-tydiro', 'Исторические приключения');
insert into genre (parent_id, slug, name) values (6, 'genre-2qbfan', 'Книги о приключениях');
insert into genre (parent_id, slug, name) values (6, 'genre-8v1ob9', 'Книги о путешествиях');
insert into genre (parent_id, slug, name) values (6, 'genre-e67n4q', 'Морские приключения');
insert into genre (parent_id, slug, name) values (6, 'genre-s3n1ol', 'Зарубежные приключения');
insert into genre (parent_id, slug, name) values (7, 'genre-ucstmx', 'Современные любовные романы');
insert into genre (parent_id, slug, name) values (7, 'genre-p26j4k', 'Остросюжетные любовные романы');
insert into genre (parent_id, slug, name) values (7, 'genre-vfjkvw', 'Эротические романы');
insert into genre (parent_id, slug, name) values (7, 'genre-watn4i', 'Зарубежные любовные романы');
insert into genre (parent_id, slug, name) values (7, 'genre-ijp0gq', 'Исторические любовные романы');
insert into genre (parent_id, slug, name) values (8, 'genre-8gclxe', 'Современная русская литература');
insert into genre (parent_id, slug, name) values (8, 'genre-my1hcv', 'Историческая литература');
insert into genre (parent_id, slug, name) values (8, 'genre-ek1831', 'Современная зарубежная литература');
insert into genre (parent_id, slug, name) values (8, 'genre-1tpfoe', 'Книги о войне');
insert into genre (parent_id, slug, name) values (8, 'genre-eali3v', 'Контркультура');
insert into genre (parent_id, slug, name) values (9, 'genre-0qbv4c', 'Пьесы и драматургия');
insert into genre (parent_id, slug, name) values (9, 'genre-q6vufn', 'Русская драматургия');
insert into genre (parent_id, slug, name) values (9, 'genre-fy5v6s', 'Зарубежная драматургия');
insert into genre (parent_id, slug, name) values (10, 'genre-h9r45a', 'Зарубежная классика');
insert into genre (parent_id, slug, name) values (10, 'genre-l3tiqy', 'Русская классика');
insert into genre (parent_id, slug, name) values (10, 'genre-b74e5t', 'Литература 19 века');
insert into genre (parent_id, slug, name) values (10, 'genre-1hmb5w', 'Зарубежная старинная литература');
insert into genre (parent_id, slug, name) values (10, 'genre-asi9wi', 'Литература 20 века');
insert into genre (parent_id, slug, name) values (11, 'genre-n1qe8k', 'Трейдинг');
insert into genre (parent_id, slug, name) values (11, 'genre-0zbwyq', 'Финансовые инструменты');
insert into genre (parent_id, slug, name) values (11, 'genre-nvzkiq', 'Корпоративные финансы');
insert into genre (parent_id, slug, name) values (11, 'genre-g6gjh1', 'Риски');
insert into genre (parent_id, slug, name) values (11, 'genre-bdpakc', 'Бюджетирование');
insert into genre (parent_id, slug, name) values (12, 'genre-h1ksel', 'Управление бизнесом');
insert into genre (parent_id, slug, name) values (12, 'genre-xhz6sr', 'Управление персоналом');
insert into genre (parent_id, slug, name) values (12, 'genre-nsyo55', 'Лидерство');
insert into genre (parent_id, slug, name) values (12, 'genre-909oky', 'Финансовый менеджмент');
insert into genre (parent_id, slug, name) values (12, 'genre-tt57jy', 'Организационный менеджмент');
insert into genre (parent_id, slug, name) values (13, 'genre-3xg4gy', 'Книги по экономике');
insert into genre (parent_id, slug, name) values (13, 'genre-t6z1ou', 'Экономическое развитие');
insert into genre (parent_id, slug, name) values (13, 'genre-aeso8x', 'Экономическая статистика');
insert into genre (parent_id, slug, name) values (13, 'genre-gghygt', 'Управление экономикой');
insert into genre (parent_id, slug, name) values (13, 'genre-7vfdzj', 'Мировая экономика');
insert into genre (parent_id, slug, name) values (14, 'genre-gxsut9', 'Критика');
insert into genre (parent_id, slug, name) values (14, 'genre-lt2k1s', 'Изобразительное искусство');
insert into genre (parent_id, slug, name) values (14, 'genre-4xubcu', 'Кинематограф / театр');
insert into genre (parent_id, slug, name) values (14, 'genre-64ho6v', 'Музыка');
insert into genre (parent_id, slug, name) values (14, 'genre-ecshq2', 'Искусствоведение');
insert into genre (parent_id, slug, name) values (15, 'genre-oa32cl', 'Гуманитарные и общественные науки');
insert into genre (parent_id, slug, name) values (15, 'genre-c5nfsd', 'Учебники и пособия для вузов');
insert into genre (parent_id, slug, name) values (15, 'genre-b8bll3', 'Естественные науки');
insert into genre (parent_id, slug, name) values (15, 'genre-5ghrih', 'Технические науки');
insert into genre (parent_id, slug, name) values (15, 'genre-rrlagg', 'Медицина / здравоохранение');
insert into genre (parent_id, slug, name) values (16, 'genre-hzbz9p', 'Программы');
insert into genre (parent_id, slug, name) values (16, 'genre-76ok88', 'Программирование');
insert into genre (parent_id, slug, name) values (16, 'genre-qn07x2', 'Базы данных');
insert into genre (parent_id, slug, name) values (16, 'genre-sftv5q', 'Интернет');
insert into genre (parent_id, slug, name) values (16, 'genre-99ry5g', 'ОС и сети');
