insert into tag (name, slug) values ('Ведьмы', 'tag-bh4s0c');
insert into tag (name, slug) values ('Борьба за выживание', 'tag-a7atwa');
insert into tag (name, slug) values ('Демоны', 'tag-b6z52c');
insert into tag (name, slug) values ('Другая планета', 'tag-0dwdt0');
insert into tag (name, slug) values ('Жизнь и смерть', 'tag-evqwuv');
insert into tag (name, slug) values ('Бытовое фэнтези', 'tag-8km7v5');
insert into tag (name, slug) values ('Антиутопия', 'tag-h69db6');
insert into tag (name, slug) values ('Альтернативная реальность', 'tag-i5vgzx');
insert into tag (name, slug) values ('Великая отечественная война', 'tag-fj6093');
insert into tag (name, slug) values ('Гендерная интрига', 'tag-bm93pe');
insert into tag (name, slug) values ('Еда', 'tag-fbssqu');
insert into tag (name, slug) values ('Еретик', 'tag-hrasuz');
insert into tag (name, slug) values ('Жестокость и насилие', 'tag-k92wt7');
insert into tag (name, slug) values ('Звёздные войны', 'tag-voqk4i');
insert into tag (name, slug) values ('Запретная любовь', 'tag-b9mxxh');
insert into tag (name, slug) values ('Искусственный интеллект', 'tag-5quuez');
insert into tag (name, slug) values ('Зомбиапокалипсис', 'tag-9iu8yr');
insert into tag (name, slug) values ('Земля', 'tag-od3otk');
insert into tag (name, slug) values ('Зима', 'tag-vt7id0');
insert into tag (name, slug) values ('Иные миры', 'tag-udy2ap');
insert into tag (name, slug) values ('Империя', 'tag-lal4dq');
insert into tag (name, slug) values ('История', 'tag-ra9vnz');
insert into tag (name, slug) values ('Космос', 'tag-p7wnu2');
insert into tag (name, slug) values ('Компьютерные игры', 'tag-sncaip');
insert into tag (name, slug) values ('Космос и будущее', 'tag-qdy0fy');
insert into tag (name, slug) values ('Любовное фэнтези', 'tag-04i4rx');
insert into tag (name, slug) values ('Любовь вопреки', 'tag-shag5g');
insert into tag (name, slug) values ('Мифология', 'tag-46yf7f');
insert into tag (name, slug) values ('Маньяк', 'tag-51lnml');
insert into tag (name, slug) values ('Монстры', 'tag-b8iu4a');
insert into tag (name, slug) values ('Месть', 'tag-9ua32c');
insert into tag (name, slug) values ('Некромант', 'tag-yxwdy8');
insert into tag (name, slug) values ('Отношения', 'tag-9dikca');
insert into tag (name, slug) values ('Откровенно', 'tag-f3occp');
insert into tag (name, slug) values ('Оборотень', 'tag-hltlir');
insert into tag (name, slug) values ('Нейросети', 'tag-vnggne');
insert into tag (name, slug) values ('Опасные приключения', 'tag-1p48m3');
insert into tag (name, slug) values ('От ненависти до любви', 'tag-073ax5');
insert into tag (name, slug) values ('Орбитальная станция', 'tag-819ca1');
insert into tag (name, slug) values ('Противостояние', 'tag-bprgjg');
insert into tag (name, slug) values ('Пришельцы', 'tag-hv93v8');
insert into tag (name, slug) values ('Расследование', 'tag-0h5utc');
insert into tag (name, slug) values ('Религия', 'tag-4206mm');
insert into tag (name, slug) values ('Ислам', 'tag-g0fgbr');
insert into tag (name, slug) values ('Утопия', 'tag-rzfwp9');
insert into tag (name, slug) values ('Упрямая героиня', 'tag-gcib5n');
insert into tag (name, slug) values ('Викинги', 'tag-x509u7');
insert into tag (name, slug) values ('Технологии', 'tag-r3ajni');
insert into tag (name, slug) values ('Харизматичный герой', 'tag-zpcdqu');
insert into tag (name, slug) values ('Шпионы', 'tag-6sdiua');
